[{"id":118019448,"iid":318,"project_id":12450835,"title":"Problem backing up to S3 (lp:#569826)","description":"[Original report](https://bugs.launchpad.net/bugs/569826) created by **pf (poon-fung)**\n```\nI tried to backup to S3 and got an error. I am running duplicity on Ubuntu\n8.0.4LTS. The same command backs up to local file system worked just fine:\n\nduplicity full --encrypt-key=$GPG_KEY --sign-key=$GPG_KEY --volsize=1024 \\\n        --archive-dir=/duplicity/archive --tempdir=/duplicity/tmp \\\n        --include=/data1 --include=/data2 --exclude=/ / file:///duplicity\n\nBut an error occuried when backing up to S3. The S3 bucket specified\nalready exists and is empty.\n\nduplicity full --encrypt-key=$GPG_KEY --sign-key=$GPG_KEY --volsize=1024 \\\n        --archive-dir=/duplicity/archive --tempdir=/duplicity/tmp \\\n    --include=/data1 --include=/data2 --exclude=/ / s3+http://mybucket-\ntest-backup\n\nHere is the console output:\n\nTraceback (most recent call last):\n  File \"/usr/bin/duplicity\", line 828, in \u003cmodule\u003e\n    with_tempdir(main)\n  File \"/usr/bin/duplicity\", line 821, in with_tempdir\n    fn()\n  File \"/usr/bin/duplicity\", line 795, in main\n    full_backup(col_stats)\n  File \"/usr/bin/duplicity\", line 336, in full_backup\n    bytes_written = write_multivol(\"full\", tarblock_iter, globals.backend)\n  File \"/usr/bin/duplicity\", line 205, in write_multivol\n    mf = manifest.Manifest().set_dirinfo()\n  File \"/usr/lib/python2.5/site-packages/duplicity/manifest.py\", line 54,\nin set_dirinfo\n    self.local_dirname = globals.local_path.name\nAttributeError: 'NoneType' object has no attribute 'name'\n\nMain action: inc\n/usr/bin/python 2.5.2 (r252:60911, Jul 31 2008, 17:28:52)\n[GCC 4.2.3 (Ubuntu 4.2.3-2ubuntu7)]\nduplicity 0.5.16 (April 21, 2009)\nLinux test1.testdomain.com 2.6.24-19-server #1 SMP Wed Aug 20 23:54:28 UTC\n2008 i686\nUsing temporary directory /duplicity/tmp/duplicity-zMjQZU-tempdir\nRegistering (mkstemp) temporary file /duplicity/tmp/duplicity-zMjQZU-\ntempdir/mkstemp-h-S85K-1\nTemp has 22722093056 available, backup will use approx 2469606195.\n0 files exist on backend\nExtracting backup chains from list of files: []\nCollection Status\n-----------------\nConnecting with backend: BotoBackend\nArchive dir: (() /duplicity/archive dir)\n\nFound 0 backup chains without signatures.\nNo backup chains with active signatures found\nNo orphaned or incomplete backup sets found.\nLast full backup date: none\nRegistering (mktemp) temporary file /duplicity/tmp/duplicity-zMjQZU-\ntempdir/mktemp-27JOP7-2\nUsing temporary directory /duplicity/archive/duplicity-HjOA7b-tempdir\nRegistering (mktemp) temporary file /duplicity/archive/duplicity-\nHjOA7b-tempdir/mktemp-e0tL_C-1\nAsyncScheduler: instantiating at concurrency 0\nRegistering (mktemp) temporary file /duplicity/tmp/duplicity-zMjQZU-\ntempdir/mktemp-FSGBBU-3\nSelecting /\nComparing () and None\nGetting delta of (() / dir) and None\nGenerating delta - new file: .\nError accessing possibly locked file /dbdata\nSelecting /duplicity\nComparing ('duplicity',) and None\nGetting delta of (('duplicity',) /duplicity dir) and None\nGenerating delta - new file: duplicity\n```","state":"closed","created_at":"2010-04-25T16:17:44.442Z","updated_at":"2022-11-02T15:50:55.323Z","closed_at":"2022-11-02T15:50:55.302Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::undecided","status::new"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":0,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/318","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":6,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/318","notes":"https://gitlab.com/api/v4/projects/12450835/issues/318/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/318/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#318","relative":"#318","full":"duplicity/duplicity#318"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118018679,"iid":262,"project_id":12450835,"title":"Duplicity doesn't save ACLs/xattrs (lp:#558385)","description":"[Original report](https://bugs.launchpad.net/bugs/558385) created by **Woland (wolandtel)**\n```\nHave an ext3 filesystem mounted with -o acl,user_xattr and directory on it\nwith some files having acls and extended attributes.\n\nduplicity --no-encryption dir file://bk\nduplicity --no-encryption file://bk res\n\nNow files in res have no ACLs nor xattrs.\n\nduplicity 0.6.08b (from distro and from sources)\n\nPython 2.5.5\n\nDebian testing GNU/Linux\n\naiur:/mnt/test# duplicity -v9 --no-encryption alfa/ file://bk\nUsing archive dir: /root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e\nUsing backup name: 31f2abd7613ded96f788766f0cbee63e\nImport of duplicity.backends.tahoebackend Succeeded\nImport of duplicity.backends.rsyncbackend Succeeded\nImport of duplicity.backends.imapbackend Succeeded\nImport of duplicity.backends.ftpbackend Succeeded\nImport of duplicity.backends.localbackend Succeeded\nImport of duplicity.backends.webdavbackend Succeeded\nImport of duplicity.backends.hsibackend Succeeded\nImport of duplicity.backends.cloudfilesbackend Succeeded\nImport of duplicity.backends.sshbackend Succeeded\nImport of duplicity.backends.giobackend Succeeded\nImport of duplicity.backends.botobackend Succeeded\nMain action: inc\n================================================================================\nduplicity 0.6.08b (March 11, 2010)\nArgs: /usr/bin/duplicity -v9 --no-encryption alfa/ file://bk\nLinux aiur 2.6.32.7-aiur #3 SMP Wed Feb 10 20:35:13 YEKT 2010 i686\n/usr/bin/python 2.5.5 (r255:77872, Feb  1 2010, 19:53:42)\n[GCC 4.4.3]\n================================================================================\nUsing temporary directory /tmp/duplicity-a5WVEO-tempdir\nRegistering (mkstemp) temporary file /tmp/duplicity-a5WVEO-tempdir/mkstemp-\nAMb2kK-1\nTemp has 249462784 available, backup will use approx 34078720.\nSynchronizing remote metadata to local cache...\nDeleting local\n/root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e/duplicity-full-\nsignatures.20100408T115330Z.sigtar.gz (not authoritative at backend).\nDeleting local\n/root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e/duplicity-\nfull.20100408T115330Z.manifest (not authoritative at backend).\n0 files exist on backend\n0 files exist in cache\nExtracting backup chains from list of files: []\nLast full backup date: none\nCollection Status\n-----------------\nConnecting with backend: LocalBackend\nArchive dir: /root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e\n\nFound 0 secondary backup chains.\nNo backup chains with active signatures found\nNo orphaned or incomplete backup sets found.\nNo signatures found, switching to full backup.\nUsing temporary directory\n/root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e/duplicity-AWuhUl-\ntempdir\nRegistering (mktemp) temporary file\n/root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e/duplicity-AWuhUl-\ntempdir/mktemp-P4y5eN-1\nUsing temporary directory\n/root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e/duplicity-\nZR3L5J-tempdir\nRegistering (mktemp) temporary file\n/root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e/duplicity-\nZR3L5J-tempdir/mktemp-OP8eXA-1\nAsyncScheduler: instantiating at concurrency 0\nRegistering (mktemp) temporary file /tmp/duplicity-a5WVEO-tempdir/mktemp-\nArJkgN-2\nSelecting alfa\nComparing () and None\nGetting delta of (() alfa dir) and None\nA .\nSelecting alfa/file\nComparing ('file',) and None\nGetting delta of (('file',) alfa/file reg) and None\nA file\nSelecting alfa/test\nComparing ('test',) and None\nGetting delta of (('test',) alfa/test reg) and None\nA test\nSelecting alfa/\nComparing ('\\xed\\xf4',) and None\nGetting delta of (('\\xed\\xf4',) alfa/reg) and None\nA\nSelecting alfa/\nComparing ('\\xf2\\xe5\\xf1\\xf2',) and None\nGetting delta of (('\\xf2\\xe5\\xf1\\xf2',) alfa/ reg) and None\nA\nRemoving still remembered temporary file\n/root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e/duplicity-AWuhUl-\ntempdir/mktemp-P4y5eN-1\nCleanup of temporary file\n/root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e/duplicity-AWuhUl-\ntempdir/mktemp-P4y5eN-1 failed\nRemoving still remembered temporary file\n/root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e/duplicity-\nZR3L5J-tempdir/mktemp-OP8eXA-1\nCleanup of temporary file\n/root/.cache/duplicity/31f2abd7613ded96f788766f0cbee63e/duplicity-\nZR3L5J-tempdir/mktemp-OP8eXA-1 failed\nAsyncScheduler: running task synchronously (asynchronicity disabled)\nWriting bk/duplicity-full.20100408T120817Z.vol1.difftar.gz\nDeleting /tmp/duplicity-a5WVEO-tempdir/mktemp-ArJkgN-2\nForgetting temporary file /tmp/duplicity-a5WVEO-tempdir/mktemp-ArJkgN-2\nAsyncScheduler: task completed successfully\nProcessed volume 1\nWriting bk/duplicity-full-signatures.20100408T120817Z.sigtar.gz\nWriting bk/duplicity-full.20100408T120817Z.manifest\n3 files exist on backend\n2 files exist in cache\nExtracting backup chains from list of files: ['duplicity-\nfull.20100408T120817Z.manifest', 'duplicity-\nfull.20100408T120817Z.vol1.difftar.gz', 'duplicity-full-\nsignatures.20100408T120817Z.sigtar.gz']\nFile duplicity-full.20100408T120817Z.manifest is not part of a known set;\ncreating new set\nFile duplicity-full.20100408T120817Z.vol1.difftar.gz is part of known set\nFile duplicity-full-signatures.20100408T120817Z.sigtar.gz is not part of a\nknown set; creating new set\nIgnoring file (rejected by backup set) 'duplicity-full-\nsignatures.20100408T120817Z.sigtar.gz'\nFound backup chain [Thu Apr  8 18:08:17 2010]-[Thu Apr  8 18:08:17 2010]\n--------------[ Backup Statistics ]--------------\nStartTime 1270728497.40 (Thu Apr  8 18:08:17 2010)\nEndTime 1270728497.42 (Thu Apr  8 18:08:17 2010)\nElapsedTime 0.01 (0.01 seconds)\nSourceFiles 5\nSourceFileSize 1024 (1.00 KB)\nNewFiles 5\nNewFileSize 1024 (1.00 KB)\nDeletedFiles 0\nChangedFiles 0\nChangedFileSize 0 (0 bytes)\nChangedDeltaSize 0 (0 bytes)\nDeltaEntries 5\nRawDeltaSize 0 (0 bytes)\nTotalDestinationSizeChange 220 (220 bytes)\nErrors 0\n-------------------------------------------------\n\nRemoving still remembered temporary file /tmp/duplicity-a5WVEO-\ntempdir/mkstemp-AMb2kK-1\n```","state":"closed","created_at":"2010-04-08T12:12:19.509Z","updated_at":"2022-11-02T16:40:03.275Z","closed_at":"2022-11-02T15:39:35.847Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::medium","status::confirmed"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":7,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/262","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":136,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/262","notes":"https://gitlab.com/api/v4/projects/12450835/issues/262/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/262/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#262","relative":"#262","full":"duplicity/duplicity#262"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019443,"iid":317,"project_id":12450835,"title":"Should detect unencypted backups even if --no-encryption omitted (lp:#550368)","description":"[Original report](https://bugs.launchpad.net/bugs/550368) created by **Olivier Berger (olivierberger)**\n```\nWhen a backup was made with --no-encryption, subsequent calls to\ncollection-status should auto-detect that it was not ecnrypted.\n\nAt the moment, issueing duplicity collection-status file:///whatever/ will\nreport an error like :\nIOError: [Errno 2] No such file or directory: '/whatever/duplicity-full-\nsignatures.20100306T090815Z.sigtar.gpg'\n\nIt could detect that there's indeed a duplicity-full-\nsignatures.20100306T090815Z.sigtar.gz instead of the .gpg file.\n\nHope this helps.\n\nBest regards,\n```","state":"closed","created_at":"2010-03-28T17:23:24.403Z","updated_at":"2022-11-02T15:50:51.584Z","closed_at":"2022-11-02T15:50:51.513Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::undecided","status::new"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":0,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/317","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":28,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/317","notes":"https://gitlab.com/api/v4/projects/12450835/issues/317/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/317/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#317","relative":"#317","full":"duplicity/duplicity#317"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019439,"iid":316,"project_id":12450835,"title":"crash on cleanup, local archive files not found remote (lp:#545823)","description":"[Original report](https://bugs.launchpad.net/bugs/545823) created by **Jelle de Jong (jelledejong)**\n```\n------------------------------------------------------------------------\n\nhttp://lists.gnu.org/archive/html/duplicity-talk/2010-03/msg00099.html\n\n------------------------------------------------------------------------\n\nhost02:~# duplicity --version\nduplicity 0.6.08b\n\n------------------------------------------------------------------------\n\nhost02:~# duplicity cleanup --extra-clean --force\nscp://host02-backup@host01.example.com/backup/vmail\nGnuPG passphrase:\nLocal and Remote metadata are synchronized, no sync needed.\nWarning, found the following remote orphaned signature files:\nduplicity-new-signatures.20100203T223035Z.to.20100204T223041Z.sigtar.gpg\nduplicity-new-signatures.20100204T223041Z.to.20100205T223035Z.sigtar.gpg\nduplicity-new-signatures.20100205T223035Z.to.20100206T223034Z.sigtar.gpg\nduplicity-new-signatures.20100206T223034Z.to.20100207T223036Z.sigtar.gpg\nduplicity-new-signatures.20100207T223036Z.to.20100208T223035Z.sigtar.gpg\nduplicity-new-signatures.20100208T223035Z.to.20100209T223042Z.sigtar.gpg\nduplicity-new-signatures.20100209T223042Z.to.20100210T223033Z.sigtar.gpg\nduplicity-new-signatures.20100210T223033Z.to.20100211T223040Z.sigtar.gpg\nduplicity-new-signatures.20100211T223040Z.to.20100212T223033Z.sigtar.gpg\nduplicity-new-signatures.20100212T223033Z.to.20100213T223037Z.sigtar.gpg\nduplicity-new-signatures.20100213T223037Z.to.20100214T223033Z.sigtar.gpg\nduplicity-new-signatures.20100214T223033Z.to.20100215T223037Z.sigtar.gpg\nduplicity-new-signatures.20100215T223037Z.to.20100216T223037Z.sigtar.gpg\nduplicity-new-signatures.20100216T223037Z.to.20100217T223037Z.sigtar.gpg\nduplicity-new-signatures.20100217T223037Z.to.20100218T223039Z.sigtar.gpg\nduplicity-new-signatures.20100218T223039Z.to.20100219T230500Z.sigtar.gpg\nduplicity-new-signatures.20100219T230500Z.to.20100311T171314Z.sigtar.gpg\nduplicity-new-signatures.20100311T171314Z.to.20100311T172255Z.sigtar.gpg\nWarning, found the following orphaned backup file:\n[duplicity-inc.20100311T173524Z.to.20100311T223101Z.manifest.part]\nLast full backup date: Fri Mar 12 23:30:52 2010\nDeleting these files from backend:\nduplicity-full-signatures.20100202T094033Z.sigtar.gz\nduplicity-new-signatures.20100202T094033Z.to.20100203T223035Z.sigtar.part\nduplicity-new-signatures.20100203T223035Z.to.20100204T223041Z.sigtar.gz\nduplicity-new-signatures.20100204T223041Z.to.20100205T223035Z.sigtar.gz\nduplicity-new-signatures.20100205T223035Z.to.20100206T223034Z.sigtar.gz\nduplicity-new-signatures.20100206T223034Z.to.20100207T223036Z.sigtar.gz\nduplicity-new-signatures.20100207T223036Z.to.20100208T223035Z.sigtar.gz\nduplicity-new-signatures.20100208T223035Z.to.20100209T223042Z.sigtar.gz\nduplicity-new-signatures.20100209T223042Z.to.20100210T223033Z.sigtar.gz\nduplicity-new-signatures.20100210T223033Z.to.20100211T223040Z.sigtar.gz\nduplicity-new-signatures.20100211T223040Z.to.20100212T223033Z.sigtar.gz\nduplicity-new-signatures.20100212T223033Z.to.20100213T223037Z.sigtar.gz\nduplicity-new-signatures.20100213T223037Z.to.20100214T223033Z.sigtar.gz\nduplicity-new-signatures.20100214T223033Z.to.20100215T223037Z.sigtar.gz\nduplicity-new-signatures.20100215T223037Z.to.20100216T223037Z.sigtar.gz\nduplicity-new-signatures.20100216T223037Z.to.20100217T223037Z.sigtar.gz\nduplicity-new-signatures.20100217T223037Z.to.20100218T223039Z.sigtar.gz\nduplicity-new-signatures.20100218T223039Z.to.20100219T230500Z.sigtar.gz\nduplicity-new-signatures.20100219T230500Z.to.20100311T171314Z.sigtar.gz\nduplicity-new-signatures.20100311T171314Z.to.20100311T172255Z.sigtar.gz\nduplicity-new-signatures.20100311T172255Z.to.20100311T173524Z.sigtar.part\nduplicity-new-signatures.20100311T173524Z.to.20100311T223101Z.sigtar.part\nduplicity-inc.20100311T173524Z.to.20100311T223101Z.manifest.part\nduplicity-full-signatures.20100202T094033Z.sigtar.gpg\nduplicity-new-signatures.20100203T223035Z.to.20100204T223041Z.sigtar.gpg\nduplicity-new-signatures.20100204T223041Z.to.20100205T223035Z.sigtar.gpg\nduplicity-new-signatures.20100205T223035Z.to.20100206T223034Z.sigtar.gpg\nduplicity-new-signatures.20100206T223034Z.to.20100207T223036Z.sigtar.gpg\nduplicity-new-signatures.20100207T223036Z.to.20100208T223035Z.sigtar.gpg\nduplicity-new-signatures.20100208T223035Z.to.20100209T223042Z.sigtar.gpg\nduplicity-new-signatures.20100209T223042Z.to.20100210T223033Z.sigtar.gpg\nduplicity-new-signatures.20100210T223033Z.to.20100211T223040Z.sigtar.gpg\nduplicity-new-signatures.20100211T223040Z.to.20100212T223033Z.sigtar.gpg\nduplicity-new-signatures.20100212T223033Z.to.20100213T223037Z.sigtar.gpg\nduplicity-new-signatures.20100213T223037Z.to.20100214T223033Z.sigtar.gpg\nduplicity-new-signatures.20100214T223033Z.to.20100215T223037Z.sigtar.gpg\nduplicity-new-signatures.20100215T223037Z.to.20100216T223037Z.sigtar.gpg\nduplicity-new-signatures.20100216T223037Z.to.20100217T223037Z.sigtar.gpg\nduplicity-new-signatures.20100217T223037Z.to.20100218T223039Z.sigtar.gpg\nduplicity-new-signatures.20100218T223039Z.to.20100219T230500Z.sigtar.gpg\nduplicity-new-signatures.20100219T230500Z.to.20100311T171314Z.sigtar.gpg\nduplicity-new-signatures.20100311T171314Z.to.20100311T172255Z.sigtar.gpg\nRemote file or directory does not exist in command='rm \"duplicity-\ninc.20100311T173524Z.to.20100311T223101Z.manifest.part\"'\nRunning 'sftp  -oServerAliveInterval=15 -oServerAliveCountMax=1\nhost02-backup@host01.example.com' failed (attempt #1)\nRemote file or directory does not exist in command='rm \"duplicity-\ninc.20100311T173524Z.to.20100311T223101Z.manifest.part\"'\nRunning 'sftp  -oServerAliveInterval=15 -oServerAliveCountMax=1\nhost02-backup@host01.example.com' failed (attempt #2)\nRemote file or directory does not exist in command='rm \"duplicity-\ninc.20100311T173524Z.to.20100311T223101Z.manifest.part\"'\nRunning 'sftp  -oServerAliveInterval=15 -oServerAliveCountMax=1\nhost02-backup@host01.example.com' failed (attempt #3)\nRemote file or directory does not exist in command='rm \"duplicity-\ninc.20100311T173524Z.to.20100311T223101Z.manifest.part\"'\nRunning 'sftp  -oServerAliveInterval=15 -oServerAliveCountMax=1\nhost02-backup@host01.example.com' failed (attempt #4)\nRemote file or directory does not exist in command='rm \"duplicity-\ninc.20100311T173524Z.to.20100311T223101Z.manifest.part\"'\nRunning 'sftp  -oServerAliveInterval=15 -oServerAliveCountMax=1\nhost02-backup@host01.example.com' failed (attempt #5)\nGiving up trying to execute 'sftp  -oServerAliveInterval=15\n-oServerAliveCountMax=1 host02-backup@host01.example.com' after 5 attempts\nBackendException: Error running 'sftp  -oServerAliveInterval=15\n-oServerAliveCountMax=1 host02-backup@host01.example.com'\n\n------------------------------------------------------------------------\n\nSee file attached to this bug report.\n\n------------------------------------------------------------------------\n```","state":"closed","created_at":"2010-03-24T08:40:46.293Z","updated_at":"2022-11-02T15:50:43.730Z","closed_at":"2022-11-02T15:50:43.713Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::undecided","status::new"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":2,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/316","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":12,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/316","notes":"https://gitlab.com/api/v4/projects/12450835/issues/316/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/316/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#316","relative":"#316","full":"duplicity/duplicity#316"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019260,"iid":293,"project_id":12450835,"title":"Should not auto-create missing target dirs (lp:#543226)","description":"[Original report](https://bugs.launchpad.net/bugs/543226) created by **Olivier Berger (olivierberger)**\n```\nHi.\n\nIt seems that duplicity desn't check and report missing destination dir,\nbut instead auto-creates it.\n\nThat may seem convenient to users, but can lead to dangerous situations.\n\nImagine that the (local) target dir is file:///mnt/sda1/backups for\ninstance, where /mnt/sda1 is a mounted volume.\n\nIf for whatever reason, the volume hasn't been mounted, then next duplicity\nrun will start writing inside the mount point directory.\n\nIt is quite common, I suppose, to use external disks of big capacity to\nrelieve the main system's disks for backups... but then it would start\nfilling-up the main system.\n\nI think a check for existance of the target dir would be the first thing to\ndo at the begining of the backup.\n\nThanks in advance.\n```","state":"closed","created_at":"2010-03-21T08:00:29.258Z","updated_at":"2022-11-02T15:47:56.536Z","closed_at":"2022-11-02T15:47:56.511Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::wishlist","status::new"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":2,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/293","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":8,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/293","notes":"https://gitlab.com/api/v4/projects/12450835/issues/293/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/293/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#293","relative":"#293","full":"duplicity/duplicity#293"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118022558,"iid":652,"project_id":12450835,"title":"Setting --tmpdir on Synology fails (lp:#532244)","description":"[Original report](https://bugs.launchpad.net/bugs/532244) created by **hasko (hasko)**\n```\nInstalled duplicity 0.6.05 on a Synology disk station. Using --tmpdir\noption and alternatively TMPDIR environment var renders the following\nmessages:\n\nGnuPG passphrase:\nLocal and Remote metadata are synchronized, no sync needed.\nLast full backup date: none\nNo signatures found, switching to full backup.\nRetype passphrase to confirm:\nCleanup of temporary directory /volume1/public/tmp/duplicity-AfRpy0-tempdir\nfailed - this is probably a bug.\nTraceback (most recent call last):\n  File \"/opt/bin/duplicity-2.6\", line 1241, in \u003cmodule\u003e\n    with_tempdir(main)\n  File \"/opt/bin/duplicity-2.6\", line 1234, in with_tempdir\n    fn()\n  File \"/opt/bin/duplicity-2.6\", line 1212, in main\n    full_backup(col_stats)\n  File \"/opt/bin/duplicity-2.6\", line 417, in full_backup\n    globals.backend)\n  File \"/opt/bin/duplicity-2.6\", line 295, in write_multivol\n    globals.gpg_profile, globals.volsize)\n  File \"/opt/lib/python2.6/site-packages/duplicity/gpg.py\", line 278, in\nGPGWriteFile\n    bytes_to_go = data_size - get_current_size()\n  File \"/opt/lib/python2.6/site-packages/duplicity/gpg.py\", line 270, in\nget_current_size\n    return os.stat(filename).st_size\nOSError: [Errno 2] No such file or directory:\n'/volume1/public/tmp/duplicity-AfRpy0-tempdir/mktemp-ZlwWIw-2'\n\nIs this me being stupid? The Synology acting up weird? A bug??\n\nPython 2.6, OS: Synology DSM 2.2-0959, target file system Amazon S3. I'll\nhappily send the longer log if necessary, i.e. if it's really an obscure\nbug.\n```","state":"closed","created_at":"2010-03-04T22:22:35.712Z","updated_at":"2022-11-02T16:28:57.048Z","closed_at":"2022-11-02T16:28:51.580Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::undecided","status::duplicate"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":3,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/652","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":28,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/652","notes":"https://gitlab.com/api/v4/projects/12450835/issues/652/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/652/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#652","relative":"#652","full":"duplicity/duplicity#652"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118018646,"iid":261,"project_id":12450835,"title":"Allow testing an exclude file (output list of files it matches) (lp:#505366)","description":"[Original report](https://bugs.launchpad.net/bugs/505366) created by **Daniel Hahler (blueyed)**\n```\nI'd like to have an interface/command to list the files that matches a\ngiven include/exclude pattern/file.\n\nUSE CASE:\nI'm facing a problem, where duplicity (0.5.06, Ubuntu Hardy) backs up far\ntoo many files, and it appears to be related to my refactoring of excludes\nin the exclude file, from:\n  + /var/lib/vz/private/111/var/lib/mysql/sqldump\n  + /var/lib/vz/private/142/var/lib/mysql/sqldump\n  /var/lib/vz/private/111/var/lib/mysql/*/\n  /var/lib/vz/private/142/var/lib/mysql/*/\nto\n  + **/var/lib/mysql/sqldump\n  **/var/lib/mysql/*/*\n  (and adding)\n  **/var/lib/mysql/ibdata1\n  **/var/lib/mysql/ib_logfile*\n\nIt would be very helpful to easily test those patterns to track this down.\n\n\n```","state":"closed","created_at":"2010-01-10T03:43:09.944Z","updated_at":"2022-11-02T15:39:02.260Z","closed_at":"2022-11-02T15:39:02.244Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::medium","status::confirmed"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":5,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/261","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":20,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/261","notes":"https://gitlab.com/api/v4/projects/12450835/issues/261/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/261/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#261","relative":"#261","full":"duplicity/duplicity#261"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019437,"iid":315,"project_id":12450835,"title":"url passwords are not escaped, duplicity crashes (lp:#504417)","description":"[Original report](https://bugs.launchpad.net/bugs/504417) created by **edso (ed.so)**\n```\nthis probably affects all data given in the url string!\n\ntext attached from original message:\nhttp://lists.gnu.org/archive/html/duplicity-talk/2009-12/msg00028.html\n\nI forward this because he is totally right and this should also be fixed\nupstream.\n\nWhat duply does from the next release (which is from today's xmas release\n;) is to url encode separately given user/password params and hinting the\nuser in the conf file that special chars have to be url encoded in the\nparts username, password, path of the url.\n\nAs duplicity can't possibly know if a user already url encoded these, it\ncan't really fix it. But it should still try to guide the user around such\nerrors.\na) I guess some note about the necessity url encoding in the error message\nwould help a lot here.\nb) Additionally the whole url could be scanned for chars that are not\nA-Za-z0-9._-~:/ . As duplicity backends do not have querystrings I guess\nany other character in the url means that the url is not valid.\n\n\n... merry days, ede\n\n\n-------- Original Message --------\nBugs item #2920707, was opened at 2009-12-24 14:28\nMessage generated for change (Tracker Item Submitted) made by nobody\nYou can respond by visiting:\nhttps://sourceforge.net/tracker/?func=detail\u0026atid=1041147\u0026aid=2920707\u0026group_id=217745\n\n\nPlease note that this message will contain a full copy of the comment\nthread,\nincluding the initial issue submission, for this request,\nnot just the latest update.\nCategory: None\nGroup: None\nStatus: Open\nResolution: None\nPriority: 5\nPrivate: No\nSubmitted By: Nobody/Anonymous (nobody)\nAssigned to: Nobody/Anonymous (nobody)\nSummary: ftp passwords are not escaped, duplicity crashes\n\nInitial Comment:\nWhen an ftp password contains special characters (in my case the ? and =\nletters), they must be encoded as %3F and %3D. Currently, neither duply not\nduplicity do the escaping, and neither of them tell the user to do it\nmanually. If they are not encoded properly, duplicity will crash with a\nrather meaningless error message. For ftplictiy V 0.5.18 it's:\n\nUser error detail: Traceback (most recent call last):\nFile \"/usr/bin/duplicity\", line 825, in \u003cmodule\u003e\nwith_tempdir(main)\nFile \"/usr/bin/duplicity\", line 818, in with_tempdir\nfn()\nFile \"/usr/bin/duplicity\", line 747, in main\naction = commandline.ProcessCommandLine(sys.argv[1:])\nFile \"/usr/lib/python2.6/dist-packages/duplicity/commandline.py\", line 593,\nin ProcessCommandLine\nbackup, local_pathname = set_backend(args[0], args[1])\nFile \"/usr/lib/python2.6/dist-packages/duplicity/commandline.py\", line 488,\nin set_backend\nbackend1, backend2 = backend.get_backend(arg1), backend.get_backend(arg2)\nFile \"/usr/lib/python2.6/dist-packages/duplicity/backend.py\", line 84, in\nget_backend\npu = ParsedUrl(url_string)\nFile \"/usr/lib/python2.6/dist-packages/duplicity/backend.py\", line 191, in\n__init__\nraise InvalidBackendURL(\"Syntax error (port) in: %s\" % url_string)\nInvalidBackendURL: Syntax error (port) in: ftp://username123:address@hidden\n\nIn duplicity 0.5.09 the error message is different, more useless, but about\nthe same type of problem.\n\nI see three possible solutions:\n* duply should encode the password properly\n* duplicity should encode the password properly\n* both duply and duplicity should state more clearly that they need pre-\nencoded passwords, so that the user knows he must do it himself\n```","state":"closed","created_at":"2010-01-07T19:17:18.329Z","updated_at":"2022-11-02T15:50:39.641Z","closed_at":"2022-11-02T15:50:39.624Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::undecided","status::new"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":1,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/315","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":10,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/315","notes":"https://gitlab.com/api/v4/projects/12450835/issues/315/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/315/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#315","relative":"#315","full":"duplicity/duplicity#315"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019435,"iid":314,"project_id":12450835,"title":"unbalanced parenthesis in password breaks duplicity (lp:#504413)","description":"[Original report](https://bugs.launchpad.net/bugs/504413) created by **edso (ed.so)**\n```\ntext from:\nhttp://lists.gnu.org/archive/html/duplicity-talk/2009-10/msg00050.html\n\nIn connection to a bug in duply i stumbled over this one in duplicity ... I\nused a password containing an unclosed parenthesis eg. 'test)foo' ... I\nalso spend some time to figure out a fix. It could be the replacement of\nline 359 in backend.py (version 0.6.05) .. here a modified version of the\nfunction. The commented line is the original. The replacement above splits\nthe url in protocol, credentials, rest and creates\n'prot://[user:address@hidden' string which should suffice for obfuscation .\nThe documentation has to be adapted of course.\n\n...ede\n\n\n--FIX--\u003e\n\n\ndef munge_password(self, commandline):\n[SNIP]\nif self.parsed_url.password:\nreturn re.sub(r'^([^:/]+)://(([^:/@]*):?([^:/@]*))@?(.*)$',\nr'\\1://\\3:address@hidden', commandline)\n#return re.sub(self.parsed_url.password, '\u003cpasswd\u003e', commandline)\nelse:\nreturn commandline\n\n\n---ERROR--\u003e\n\n\nTraceback (most recent call last):\nFile \"/srv/www/vhosts/jamoke.net/_apps/duplicity-0.6.05/bin/duplicity\",\nline 1242, in \u003cmodule\u003e\nwith_tempdir(main)\nFile \"/srv/www/vhosts/jamoke.net/_apps/duplicity-0.6.05/bin/duplicity\",\nline 1235, in with_tempdir\nfn()\nFile \"/srv/www/vhosts/jamoke.net/_apps/duplicity-0.6.05/bin/duplicity\",\nline 1136, in main\nsync_archive()\nFile \"/srv/www/vhosts/jamoke.net/_apps/duplicity-0.6.05/bin/duplicity\",\nline 915, in sync_archive\nremlist = globals.backend.list()\nFile\n\"/srv/www/vhosts/jamoke.net/_apps/duplicity-0.6.05/duplicity/backends/ftpbackend.py\",\nline 109, in list\nl = self.popen_persist(commandline).split('\n')\nFile\n\"/srv/www/vhosts/jamoke.net/_apps/duplicity-0.6.05/bin/../duplicity/backend.py\",\nline 416, in popen_persist\nprivate = self.munge_password(commandline)\nFile\n\"/srv/www/vhosts/jamoke.net/_apps/duplicity-0.6.05/bin/../duplicity/backend.py\",\nline 360, in munge_password\nreturn re.sub(self.parsed_url.password, '\u003cpasswd\u003e', commandline)\nFile \"/usr/lib/python2.6/re.py\", line 150, in sub\nreturn _compile(pattern, 0).sub(repl, string, count)\nFile \"/usr/lib/python2.6/re.py\", line 243, in _compile\nraise error, v # invalid expression\nerror: unbalanced parenthesis\n```","state":"closed","created_at":"2010-01-07T19:12:20.822Z","updated_at":"2022-11-02T15:50:36.359Z","closed_at":"2022-11-02T15:50:36.335Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::undecided","status::new"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":0,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/314","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":10,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/314","notes":"https://gitlab.com/api/v4/projects/12450835/issues/314/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/314/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#314","relative":"#314","full":"duplicity/duplicity#314"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118022276,"iid":639,"project_id":12450835,"title":"Unknown error while uploading duplicity-full-signatures (lp:#502609)","description":"[Original report](https://bugs.launchpad.net/bugs/502609) created by **Olivier Berger (olivierberger)**\n```\nHi,\nI'am using Déjà dup since few days. I found it really convenient BTW :)\nSo, i was uploading my files since days and it finally reach 100% this\nmorning. It was now uploading a duplicity-full-signatures file and i had to\nstop at 1,3G to continue later on.\n\nNow when i restart Déjà-Dup i have an 'unknown error'. I suppose it's a\nBUG.. I attached the log and config file\n\nHere my version :\ndeja-dup        11.1-0ubuntu0karmic1\nduplicity       0.6.06-0ubuntu0karmic1\nDescription:    Ubuntu 9.10\n\nthanks indeed !\n```","state":"closed","created_at":"2010-01-03T14:30:08.456Z","updated_at":"2022-11-02T16:40:30.065Z","closed_at":"2022-11-02T16:24:58.102Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::undecided","status::duplicate"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":20,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/639","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":26,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/639","notes":"https://gitlab.com/api/v4/projects/12450835/issues/639/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/639/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#639","relative":"#639","full":"duplicity/duplicity#639"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019433,"iid":313,"project_id":12450835,"title":"IMAP Backend Error in _prepareBody (with python 2.4) (lp:#500902)","description":"[Original report](https://bugs.launchpad.net/bugs/500902) created by **Mickey Knox (mickey-knox)**\n```\nHi,\n\non an older system i have the following error.\n\nduplicity 0.6.06\npython 2.4.4\n\nArgs: /usr/bin/duplicity --verbosity 9 --encrypt-key FFFFFFFF --sign-key\nFFFFFFFF --gpg-opti\nons= --exclude-globbing-filelist /root/.duply/some/exclude /var/www\nimaps://someone%40g\nooglemail.com:somepass@imap.googlemail.com\n\nTraceback (most recent call last):\n  File \"/usr/bin/duplicity\", line 1236, in ?\n    with_tempdir(main)\n  File \"/usr/bin/duplicity\", line 1229, in with_tempdir\n    fn()\n  File \"/usr/bin/duplicity\", line 1207, in main\n    full_backup(col_stats)\n  File \"/usr/bin/duplicity\", line 416, in full_backup\n    globals.backend)\n  File \"/usr/bin/duplicity\", line 315, in write_multivol\n    (tdp, dest_filename)))\n  File \"/usr/lib/python2.4/site-packages/duplicity/asyncscheduler.py\", line\n148, in schedule\n_task\n    return self.__run_synchronously(fn, params)\n  File \"/usr/lib/python2.4/site-packages/duplicity/asyncscheduler.py\", line\n175, in __run_sy\nnchronously\n    ret = fn(*params)\n  File \"/usr/bin/duplicity\", line 314, in \u003clambda\u003e\n    async_waiters.append(io_scheduler.schedule_task(lambda tdp,\ndest_filename: put(tdp, dest\n_filename),\n  File \"/usr/bin/duplicity\", line 240, in put\n    backend.put(tdp, dest_filename)\n  File \"/usr/lib/python2.4/site-\npackages/duplicity/backends/imapbackend.py\", line 131, in pu\nt\n    body=self._prepareBody(f,remote_filename)\n  File \"/usr/lib/python2.4/site-\npackages/duplicity/backends/imapbackend.py\", line 103, in _p\nrepareBody\n    mp = email.MIMEMultipart.MIMEMultipart()\nAttributeError: 'module' object has no attribute 'MIMEMultipart'\n```","state":"closed","created_at":"2009-12-28T01:24:19.258Z","updated_at":"2022-11-02T15:50:33.175Z","closed_at":"2022-11-02T15:50:33.157Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::undecided","status::new"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":0,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/313","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":6,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/313","notes":"https://gitlab.com/api/v4/projects/12450835/issues/313/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/313/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#313","relative":"#313","full":"duplicity/duplicity#313"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118022268,"iid":638,"project_id":12450835,"title":"IMAP Backend Error in put() if manifest-file larger than --volsize (lp:#500901)","description":"[Original report](https://bugs.launchpad.net/bugs/500901) created by **Mickey Knox (mickey-knox)**\n```\nHi,\n\nim still trying to get duplicity to work with imap backend with a\ngooglemail.com account.\n\nUnfortunatly i receive the following error:\n\nduplicity 0.6.06\npython 2.5.2\n\nArgs: /usr/bin/duplicity --verbosity 9 --encrypt-key 7FFFAFFF --sign-key\nFFFFFF9\nC --gpg-options= --exclude-globbing-filelist /root/.duply/someconf/exclude\n/ imaps:/\n/someone%40googlemail.com:somepass@imap.gmail.com/somedir/\n\nTraceback (most recent call last):\n  File \"/usr/bin/duplicity\", line 1236, in \u003cmodule\u003e\n    with_tempdir(main)\n  File \"/usr/bin/duplicity\", line 1229, in with_tempdir\n    fn()\n  File \"/usr/bin/duplicity\", line 1207, in main\n    full_backup(col_stats)\n  File \"/usr/bin/duplicity\", line 416, in full_backup\n    globals.backend)\n  File \"/usr/bin/duplicity\", line 315, in write_multivol\n    (tdp, dest_filename)))\n  File \"/usr/lib/python2.5/site-packages/duplicity/asyncscheduler.py\", line\n148, in schedule_task\n    return self.__run_synchronously(fn, params)\n  File \"/usr/lib/python2.5/site-packages/duplicity/asyncscheduler.py\", line\n175, in __run_synchronously\n    ret = fn(*params)\n  File \"/usr/bin/duplicity\", line 314, in \u003clambda\u003e\n    async_waiters.append(io_scheduler.schedule_task(lambda tdp,\ndest_filename: put(tdp, dest_filename),\n  File \"/usr/bin/duplicity\", line 240, in put\n    backend.put(tdp, dest_filename)\n  File \"/usr/lib/python2.5/site-\npackages/duplicity/backends/imapbackend.py\", line 135, in put\n    self._conn.append(globals.imap_mailbox, None, None, body)\n  File \"/usr/lib/python2.5/imaplib.py\", line 318, in append\n    return self._simple_command(name, mailbox, flags, date_time)\n  File \"/usr/lib/python2.5/imaplib.py\", line 1055, in _simple_command\n    return self._command_complete(name, self._command(name, *args))\n  File \"/usr/lib/python2.5/imaplib.py\", line 892, in _command_complete\n    raise self.error('%s command error: %s %s' % (name, typ, data))\nerror: APPEND command error: BAD ['Could not parse command']\n```","state":"closed","created_at":"2009-12-28T01:16:52.775Z","updated_at":"2022-11-02T16:24:55.744Z","closed_at":"2022-11-02T16:24:44.871Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::undecided","status::duplicate"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":6,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/638","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":12,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/638","notes":"https://gitlab.com/api/v4/projects/12450835/issues/638/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/638/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#638","relative":"#638","full":"duplicity/duplicity#638"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118018456,"iid":260,"project_id":12450835,"title":"Crash when restoring data KeyError (lp:#498933)","description":"[Original report](https://bugs.launchpad.net/bugs/498933) created by **Michael Terry (mterry)**\n```\nBinary package hint: deja-dup\n\n1) Ubuntu 9.10\n2) Deja Dup 10.2-0ubuntu1.1\n3) I expected my backup to be restored\n4) Deja Dup crashed instead.\n\nI just tried to restore the backup I made, and it crashes repeatedly when\ntrying to restore.\n\nI have it setup to backup my home directory, and tried restoring to both\nthe original location as well as a completely different folder. Both lead\nto the same error message.\n\n\nTraceback (most recent call last):\n  File \"/usr/bin/duplicity\", line 825, in \u003cmodule\u003e\n    with_tempdir(main)\n  File \"/usr/bin/duplicity\", line 818, in with_tempdir\n    fn()\n  File \"/usr/bin/duplicity\", line 775, in main\n    restore(col_stats)\n  File \"/usr/bin/duplicity\", line 436, in restore\n    restore_get_patched_rop_iter(col_stats)):\n  File \"/usr/lib/python2.6/dist-packages/duplicity/patchdir.py\", line 521,\nin Write_ROPaths\n    ITR(ropath.index, ropath)\n  File \"/usr/lib/python2.6/dist-packages/duplicity/lazy.py\", line 336, in\n__call__\n    last_branch.fast_process, args)\n  File \"/usr/lib/python2.6/dist-packages/duplicity/robust.py\", line 38, in\ncheck_common_error\n    return function(*args)\n  File \"/usr/lib/python2.6/dist-packages/duplicity/patchdir.py\", line 574,\nin fast_process\n    ropath.copy(self.base_path.new_index(index))\n  File \"/usr/lib/python2.6/dist-packages/duplicity/path.py\", line 412, in\ncopy\n    other.writefileobj(self.open(\"rb\"))\n  File \"/usr/lib/python2.6/dist-packages/duplicity/path.py\", line 574, in\nwritefileobj\n    buf = fin.read(_copy_blocksize)\n  File \"/usr/lib/python2.6/dist-packages/duplicity/patchdir.py\", line 199,\nin read\n    if not self.addtobuffer():\n  File \"/usr/lib/python2.6/dist-packages/duplicity/patchdir.py\", line 224,\nin addtobuffer\n    self.tarinfo_list[0] = self.tar_iter.next()\n  File \"/usr/lib/python2.6/dist-packages/duplicity/patchdir.py\", line 331,\nin next\n    self.set_tarfile()\n  File \"/usr/lib/python2.6/dist-packages/duplicity/patchdir.py\", line 320,\nin set_tarfile\n    self.current_fp = self.fileobj_iter.next()\n  File \"/usr/bin/duplicity\", line 472, in get_fileobj_iter\n    backup_set.volume_name_dict[vol_num],\nKeyError: 15\n\nProblemType: Bug\nArchitecture: i386\nDate: Sun Dec 20 19:59:06 2009\nDistroRelease: Ubuntu 9.10\nExecutablePath: /usr/bin/deja-dup\nInstallationMedia: Ubuntu 9.10 \"Karmic Koala\" - Release i386 (20091028.5)\nPackage: deja-dup 10.2-0ubuntu1.1\nProcEnviron:\n LANG=en_US.UTF-8\n SHELL=/bin/bash\nProcVersionSignature: Ubuntu 2.6.31-16.53-generic\nSourcePackage: deja-dup\nUname: Linux 2.6.31-16-generic i686\n```\nOriginal tags: apport-bug i386","state":"closed","created_at":"2009-12-21T04:03:48.591Z","updated_at":"2022-11-02T16:28:11.240Z","closed_at":"2022-11-02T15:35:00.603Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::critical","status::as-designed"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":51,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/260","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":84,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/260","notes":"https://gitlab.com/api/v4/projects/12450835/issues/260/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/260/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#260","relative":"#260","full":"duplicity/duplicity#260"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118018450,"iid":259,"project_id":12450835,"title":"Should not exit during restore when timeout ocours (lp:#494677)","description":"[Original report](https://bugs.launchpad.net/bugs/494677) created by **Tokuko (launchpad-net-tokuko)**\n```\nHi,\n\nhumyo.de seems to be a bit buggy sometimes and in some cases seems to\ntimeout.\nA restore should not fail just because one timeout occoured, duplicity\nshould just retry the retrieve the file.\nThe file being restored is severall gigabytes (a VMWare harddisk), so\nhaving to restart the restore results in a couple of gigabytes additional\ndownload.\n\nRegards,\nTokudan\n\nduplicity 0.6.06\nPython 2.6.2\nDISTRIB_ID=Ubuntu\nDISTRIB_RELEASE=9.04\nDISTRIB_CODENAME=jaunty\nDISTRIB_DESCRIPTION=\"Ubuntu 9.04\"\nlocal Filesystem:\nFilesystem            Size  Used Avail Use% Mounted on\n/dev/sda3             219G  8.9G  199G   5% /\n/dev/sda3 on / type ext3 (rw,relatime)\n\nTraceback:\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/duplicity\", line 1236, in \u003cmodule\u003e\n    with_tempdir(main)\n  File \"/usr/local/bin/duplicity\", line 1229, in with_tempdir\n    fn()\n  File \"/usr/local/bin/duplicity\", line 1183, in main\n    restore(col_stats)\n  File \"/usr/local/bin/duplicity\", line 538, in restore\n    restore_get_patched_rop_iter(col_stats)):\n  File \"/usr/local/lib/python2.6/dist-packages/duplicity/patchdir.py\", line\n518, in Write_ROPaths\n    for ropath in rop_iter:\n  File \"/usr/local/lib/python2.6/dist-packages/duplicity/patchdir.py\", line\n491, in integrate_patch_iters\n    final_ropath = patch_seq2ropath(normalize_ps(patch_seq))\n  File \"/usr/local/lib/python2.6/dist-packages/duplicity/patchdir.py\", line\n471, in patch_seq2ropath\n    misc.copyfileobj(current_file, tempfp)\n  File \"/usr/local/lib/python2.6/dist-packages/duplicity/misc.py\", line\n166, in copyfileobj\n    buf = infp.read(blocksize)\n  File \"/usr/local/lib/python2.6/dist-packages/duplicity/patchdir.py\", line\n198, in read\n    if not self.addtobuffer():\n  File \"/usr/local/lib/python2.6/dist-packages/duplicity/patchdir.py\", line\n223, in addtobuffer\n    self.tarinfo_list[0] = self.tar_iter.next()\n  File \"/usr/local/lib/python2.6/dist-packages/duplicity/patchdir.py\", line\n330, in next\n    self.set_tarfile()\n  File \"/usr/local/lib/python2.6/dist-packages/duplicity/patchdir.py\", line\n319, in set_tarfile\n    self.current_fp = self.fileobj_iter.next()\n  File \"/usr/local/bin/duplicity\", line 575, in get_fileobj_iter\n    manifest.volume_info_dict[vol_num])\n  File \"/usr/local/bin/duplicity\", line 596, in restore_get_enc_fileobj\n    backend.get(filename, tdp)\n  File \"/usr/local/lib/python2.6/dist-\npackages/duplicity/backends/webdavbackend.py\", line 234, in get\n    response = self.request(\"GET\", url)\n  File \"/usr/local/lib/python2.6/dist-\npackages/duplicity/backends/webdavbackend.py\", line 108, in request\n    response = self.conn.getresponse()\n  File \"/usr/lib/python2.6/httplib.py\", line 950, in getresponse\n    response.begin()\n  File \"/usr/lib/python2.6/httplib.py\", line 390, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python2.6/httplib.py\", line 348, in _read_status\n    line = self.fp.readline()\n  File \"/usr/lib/python2.6/socket.py\", line 395, in readline\n    data = recv(1)\n  File \"/usr/lib/python2.6/ssl.py\", line 96, in \u003clambda\u003e\n    self.recv = lambda buflen=1024, flags=0: SSLSocket.recv(self, buflen,\nflags)\n  File \"/usr/lib/python2.6/ssl.py\", line 222, in recv\n    raise x\nSSLError: The read operation timed out\n```","state":"closed","created_at":"2009-12-09T19:26:20.504Z","updated_at":"2022-11-02T15:34:55.961Z","closed_at":"2022-11-02T15:34:55.945Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::medium","status::confirmed"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":0,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/259","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":8,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/259","notes":"https://gitlab.com/api/v4/projects/12450835/issues/259/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/259/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#259","relative":"#259","full":"duplicity/duplicity#259"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118022485,"iid":646,"project_id":12450835,"title":"Resuming an interrupted backup appears successful - but can’t restore from it (0.6.06) (lp:#491971)","description":"[Original report](https://bugs.launchpad.net/bugs/491971) created by **Matthew Twomey (mtwomey)**\n```\nI'm doing backups using openssh scp/sftp to a remote host. When a full\nbackup is\ndisrupted in the middle of transferring and then restarted - Duplicity\nstarts on the next volume number *without* finishing the files that were\nsupposed to be in the previous volume.\n\nThat is to say:\n\n*Normal non-disrupted backup*\n\nVolume 1 = files 01 - 10\nVolume 2 = files 11 - 20\nVolume 3 = files 21 - 30\n\n*Backup which was disrupted during network transfer of Volume 2 and then\nrestarted (Restarting after volume 2\" was the message in the log)*\n\nVolume 1 = files 01 - 10\nVolume 2 = files 11 - 13 (or wherever it was disrupted)\nVolume 3 = files 21 - 30\n\nI've noticed that after a disruption, if I go in and delete the last volume\nfile (the one which was disrupted) on the remote location and then restart\nthe backup - it picks up with that volume, producing a usable backup. If I\ndon't delete the file, the restore process will error out when it get to\nthe volume that was disrupted.\n\nDuplicity appears to expect temporary filenames to be used by the\nOS/transfer software during transfer, which openssh does not use by\ndefault.\n```","state":"closed","created_at":"2009-12-03T16:13:14.647Z","updated_at":"2022-11-04T16:53:06.779Z","closed_at":"2022-11-02T16:27:32.589Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::medium","status::duplicate"],"milestone":null,"assignees":[{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"}],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"user_notes_count":3,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/646","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":42,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/646","notes":"https://gitlab.com/api/v4/projects/12450835/issues/646/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/646/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#646","relative":"#646","full":"duplicity/duplicity#646"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118017933,"iid":255,"project_id":12450835,"title":"Restore fails with \"Invalid data - SHA1 hash mismatch\" (lp:#487720)","description":"[Original report](https://bugs.launchpad.net/bugs/487720) created by **Andrew Fister (andrewfister)**\n```\nWhen restoring a backup, one might see an error like:\n\nInvalid data - SHA1 hash mismatch:\nCalculated hash: 0b2bc4c2fb98b36f9891f9172f909d70ab5662e9\nManifest hash: 11cd330357618de52e4e5361a6e63b09ee951ae2\n\nThis can happen when a volume file was not completely written to the\nbackend before duplicity was interrupted (say, shutting down the machine or\nwhatever).  When duplicity resumes the backup next run, it will start with\nthe next volume.  The half-complete volume file will sit on the backend and\ncause this error later when restoring.\n\nYou can manually recover from this by either restoring from your older\nbackup sets or by restoring individual files that don't happen to be in the\ncorrupted volume.\n\n== To Reproduce ==\n\nSee attachment\nhttps://bugs.launchpad.net/ubuntu/+source/duplicity/+bug/487720/+attachment/2159465/+files/test.sh\nfor a test script tor reproduce the problem.\n\n== Ubuntu SRU Justification ==\n\nThis is a serious data loss problem for users, which won't be noticed until\nthey try to restore.  With Ubuntu 11.10 including Deja Dup, some users may\nthink to back up their data first then upgrade, and may accidentally create\ncorrupted backups.\n```\nOriginal tags: verification-done-lucid verification-done-natty verification-needed","state":"closed","created_at":"2009-11-24T17:31:01.301Z","updated_at":"2022-11-02T16:40:00.527Z","closed_at":"2022-11-02T15:28:16.246Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::critical","status::as-designed"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":65,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/255","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":204,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/255","notes":"https://gitlab.com/api/v4/projects/12450835/issues/255/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/255/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#255","relative":"#255","full":"duplicity/duplicity#255"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019258,"iid":292,"project_id":12450835,"title":"error verbosity: include filename in output, make traceback less prominent (lp:#455081)","description":"[Original report](https://bugs.launchpad.net/bugs/455081) created by **az (az-debian)**\n```\ni've got a backup of a large samba share which every now and then fails,\napparently because\nof files being modified/truncated while duplicity is accessing them:\nduplicity\ndies with a permission denied on reading (all fair and square).\n\nthe bug here is that the exception info is extremely verbose wrt.\nduplicity's calling stack but\ncompletely lacks information useful to the user - like the name/path of the\nfile that causes the\nproblem.\n\nthe information given with the default verbosity level should at least\ninclude the relevant information\n(like the path here), and ideally not expose too much of the innards to an\nend user - the traceback\nisn't useful unless you're a duplicity developer and might be restricted to\nhigher verbosity levels.\n\nhere's the relevant output:\n---\nLocal and Remote metadata are synchronized, no sync needed.\nLast full backup date: Fri Oct  9 23:25:48 2009\nTraceback (most recent call last):\n  File \"/usr/bin/duplicity\", line 1241, in \u003cmodule\u003e\n    with_tempdir(main)\n  File \"/usr/bin/duplicity\", line 1234, in with_tempdir\n    fn()\n  File \"/usr/bin/duplicity\", line 1216, in main\n    incremental_backup(sig_chain)\n  File \"/usr/bin/duplicity\", line 488, in incremental_backup\n    globals.backend)\n  File \"/usr/bin/duplicity\", line 295, in write_multivol\n    globals.gpg_profile, globals.volsize)\n  File \"/usr/lib/python2.5/site-packages/duplicity/gpg.py\", line 282, in\nGPGWriteFile\n    data = block_iter.next(min(block_size, bytes_to_go)).data\n  File \"/usr/lib/python2.5/site-packages/duplicity/diffdir.py\", line 510,\nin next\n    result = self.process(self.input_iter.next(), size)\n  File \"/usr/lib/python2.5/site-packages/duplicity/diffdir.py\", line 636,\nin process\n    data, last_block = self.get_data_block(fp, size - 512)\n  File \"/usr/lib/python2.5/site-packages/duplicity/diffdir.py\", line 663,\nin get_data_block\n    buf = fp.read(read_size)\n  File \"/usr/lib/python2.5/site-packages/duplicity/diffdir.py\", line 420,\nin read\n    buf = self.infile.read(length)\n  File \"/usr/lib/python2.5/site-packages/duplicity/diffdir.py\", line 389,\nin read\n    buf = self.infile.read(length)\nIOError: [Errno 13] Permission denied\n---\n```","state":"closed","created_at":"2009-10-19T00:55:59.311Z","updated_at":"2022-11-02T15:47:53.943Z","closed_at":"2022-11-02T15:47:53.924Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::wishlist","status::confirmed"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":0,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/292","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":6,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/292","notes":"https://gitlab.com/api/v4/projects/12450835/issues/292/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/292/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#292","relative":"#292","full":"duplicity/duplicity#292"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019427,"iid":312,"project_id":12450835,"title":"wishlist: differential backups (lp:#450885)","description":"[Original report](https://bugs.launchpad.net/bugs/450885) created by **az (az-debian)**\n```\nthis is a forward/copy of debian bug #550698 (which lives here:\nhttp://bugs.debian.org/550698)\nwhere the requester asks for differential backups to shorten the backup\nchain.\n\nthe requester, however, also asks for full control over which earlier\nbackup\nto use as base (for example a differential against an incremental backup)\nwhich i don't believe makes much sense.\n\nhere's a copy of the request:\n---cut---\nI like how duplicity works, but having overlong backup chains to conserve\nbandwidth/space puts too much pressure on the reliability of the remote\ndestination. I would like to keep the chains shorter, but can't due to\nspace\nconstraints as the only alternative is a periodic full backup.\n\nIs there a reason as of why \"incremental\" could not accept a \"-t\" argument\nto\nspecify which archive to use as the previous archive and let me manage the\nstorage by myself?\n\nIf I had a time or filename specifier like this, I could implement a\ndifferential backup script on top of duplicity without any special handling\non\nduplicity's part, much in the same way as you implement differential tar\narchives.\n\nAs long as \"restore\" walks the backup chain from the most recent volume, it\nshould also work unchanged.\n\nI've seen some old comments in the duplicity mailing list, but no proper\nfeature request. I'm also filing this here for other Debian users to see,\nsince the inability to perform differential archives kinds-of defeats the\ninitial space gain you have with duplicicy.\n\n---cut---\n```","state":"closed","created_at":"2009-10-14T01:28:10.899Z","updated_at":"2022-11-02T15:50:27.818Z","closed_at":"2022-11-02T15:50:27.797Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::undecided","status::new"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":2,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/312","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":42,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/312","notes":"https://gitlab.com/api/v4/projects/12450835/issues/312/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/312/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#312","relative":"#312","full":"duplicity/duplicity#312"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118018439,"iid":258,"project_id":12450835,"title":"Missing volume file is not detected properly (lp:#447480)","description":"[Original report](https://bugs.launchpad.net/bugs/447480) created by **Kenneth Loafman (kenneth-loafman)**\n```\nWhen I do a backup ( local folder to local folder, any options ) and delete\none of the archive files ( e.g. \"duplicity-\nfull.20091008T074524Z.vol2.difftar.gpg\" ) another call of duplicity will\nadd some files, but not the data that has been deleted before ( e.g. 25 MB\nare lost ). This leaves an incomplete backup folder which doesn`t seem\nright to me. After doing a backup with duplicity without it spitting out an\nerror message the backup archive is expected to be sane / complete.\n\n```","state":"closed","created_at":"2009-10-09T19:04:09.959Z","updated_at":"2022-11-02T15:34:47.282Z","closed_at":"2022-11-02T15:34:47.261Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::medium","status::confirmed"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":1,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/258","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":20,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/258","notes":"https://gitlab.com/api/v4/projects/12450835/issues/258/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/258/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#258","relative":"#258","full":"duplicity/duplicity#258"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019254,"iid":291,"project_id":12450835,"title":"Allow restricting list-current-files (lp:#432104)","description":"[Original report](https://bugs.launchpad.net/bugs/432104) created by **Michael Terry (mterry)**\n```\nWhen calling list-current-files, it would be nice if one could pass a\nregexp for either files one is interested in or files one is not interested\nin.  Maybe reuse the exclude/include arguments?\n\nI could grep the output, but I suspect that's wasting time/resources to\nlist everything then exclude.\n```","state":"closed","created_at":"2009-09-17T20:27:21.427Z","updated_at":"2022-11-02T15:47:51.203Z","closed_at":"2022-11-02T15:47:51.182Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::wishlist","status::new"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":0,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/291","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":20,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/291","notes":"https://gitlab.com/api/v4/projects/12450835/issues/291/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/291/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#291","relative":"#291","full":"duplicity/duplicity#291"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019253,"iid":290,"project_id":12450835,"title":"Wishlist: Report size of backup (collection-status,list-files,...) (lp:#432092)","description":"[Original report](https://bugs.launchpad.net/bugs/432092) created by **Michael Terry (mterry)**\n```\nWhen restoring, it would be nice to know the size of the backup.  I know\nthis is difficult because everything is gzipped up.  But I imagine either\nthere's a decent estimation that could be provided (the reported size\ndoesn't need to be 100% accurate, but hopefully errs on the side of over-\nreporting), or duplicity could keep track via its metadata as incrementals\nare added.\n\nOnce duplicity knows this, it can give an error if the destination is not\nlarge enough to contain it.\n\nAdditionally, it would be nice if it was reported in, say, a collection-\nstatus so that wrappers like Deja Dup could meaningfully use it.\n```","state":"closed","created_at":"2009-09-17T20:10:33.941Z","updated_at":"2022-11-02T15:47:48.202Z","closed_at":"2022-11-02T15:47:48.185Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::wishlist","status::new"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":0,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/290","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":52,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/290","notes":"https://gitlab.com/api/v4/projects/12450835/issues/290/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/290/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#290","relative":"#290","full":"duplicity/duplicity#290"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019247,"iid":289,"project_id":12450835,"title":"Add to deja-dup wake on lan functionality (lp:#431219)","description":"[Original report](https://bugs.launchpad.net/bugs/431219) created by **emilio (emiliomaggio)**\n```\nAnother item that I would like to add to the wish-list.\n\nI have recently installed a low-power home server that is the target of my\nbackups. In general (As many users I guess) I am not at home for most of\nthe day and to save even more power (and the planet :-) ) I can set up the\nserver to go in S3 sleep mode if no processes are running and I can\nmanually wake-on-lan whenever I want the server up and running.\n\nIn case of duplicity I should not care to know when the backup is happening\nand it would be great if duplicity could do the wake-up for me.\n```","state":"closed","created_at":"2009-09-17T07:31:08.669Z","updated_at":"2022-11-02T15:47:36.891Z","closed_at":"2022-11-02T15:47:36.871Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::wishlist","status::confirmed"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":6,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/289","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":40,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/289","notes":"https://gitlab.com/api/v4/projects/12450835/issues/289/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/289/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#289","relative":"#289","full":"duplicity/duplicity#289"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118018418,"iid":257,"project_id":12450835,"title":"incomplete chown() error msgs (lp:#415619)","description":"[Original report](https://bugs.launchpad.net/bugs/415619) created by **az (az-debian)**\n```\nthis is a forward/copy of debian bug #541788 (http://bugs.debian.org/cgi-\nbin/bugreport.cgi?bug=541788):\n---\nPackage: duplicity\nVersion: 0.5.16-1~bpo50+1\nSeverity: normal\n\nWhile running a test restore, duplicity reported these errors:\n\nError '[Errno 1] Operation not permitted: 'git/export'' processing export\nError '[Errno 1] Operation not permitted: 'git/hover.git/git-daemon-export-\nok''\nprocessing hover.git/git-daemon-export-ok\nError '[Errno 1] Operation not permitted: 'git/irssi.git/git-daemon-export-\nok''\nprocessing irssi.git/git-daemon-export-ok\nError '[Errno 1] Operation not permitted: 'git'' processing .\n\nThe files in question are owned by root on the source machine, the\nduplicity\nrestore test was run on another machine using a non-root account.\n\nI am guessing that the the reported failed operation is chown() as the\nfiles\nstill belong to the user running the restore.\n\nDuplicity should log which operation failed, including all details, e.g.\n\"setting owner to root:root\" or similar.\n---\n```","state":"closed","created_at":"2009-08-18T21:58:20.065Z","updated_at":"2022-11-02T16:40:02.936Z","closed_at":"2022-11-02T15:34:27.564Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::medium","status::confirmed"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":5,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/257","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":62,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/257","notes":"https://gitlab.com/api/v4/projects/12450835/issues/257/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/257/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#257","relative":"#257","full":"duplicity/duplicity#257"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null},{"id":118019168,"iid":282,"project_id":12450835,"title":"Support http_proxy (lp:#409739)","description":"[Original report](https://bugs.launchpad.net/bugs/409739) created by **Michael Terry (mterry)**\n```\nBinary package hint: deja-dup\n\nI'm using my own S3 server.  deja-dup does not support setting the S3\nserver\n(i.e., it appears to be hard coded to use aws.amazon.com).  Generally this\nis not\na problem if the program would respect the http proxy setting, however,\ndeja-dup\ndoes not appear to do this.  When I run deja-dup as follows:\n\n  http_proxy=http://localhost:8080 deja-dup\n\nit fails and I do not see any access attempts in my S3 server's logs.\n\nThanks.\n\nProblemType: Bug\nArchitecture: i386\nDistroRelease: Ubuntu 9.04\nExecutablePath: /usr/bin/deja-dup\nPackage: deja-dup 7.4-0ubuntu2\nProcEnviron:\n SHELL=/bin/bash\n PATH=(custom, user)\n LANG=en_US.UTF-8\nSourcePackage: deja-dup\nUname: Linux 2.6.28-14-generic i686\n```\nOriginal tags: apport-bug i386","state":"closed","created_at":"2009-08-06T08:34:52.749Z","updated_at":"2022-11-02T15:46:06.321Z","closed_at":"2022-11-02T15:46:06.298Z","closed_by":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"labels":["priority::low","status::as-designed"],"milestone":null,"assignees":[],"author":{"id":2708575,"username":"AlphaPrime","name":"Kenneth Loafman","state":"active","avatar_url":"https://secure.gravatar.com/avatar/a6fba0169484daeff7768831fd18acd9?s=80\u0026d=identicon","web_url":"https://gitlab.com/AlphaPrime"},"type":"ISSUE","assignee":null,"user_notes_count":8,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"https://gitlab.com/duplicity/duplicity/-/issues/282","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":14,"blocking_issues_count":0,"has_tasks":true,"task_status":"0 of 0 checklist items completed","_links":{"self":"https://gitlab.com/api/v4/projects/12450835/issues/282","notes":"https://gitlab.com/api/v4/projects/12450835/issues/282/notes","award_emoji":"https://gitlab.com/api/v4/projects/12450835/issues/282/award_emoji","project":"https://gitlab.com/api/v4/projects/12450835","closed_as_duplicate_of":null},"references":{"short":"#282","relative":"#282","full":"duplicity/duplicity#282"},"severity":"UNKNOWN","moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null,"iteration":null,"health_status":null}]